version: '3'
services:
  db_postgres:
    image: postgres:11.2
    networks:
      - sonarnet
    ports:
      - "5432:5432"
    volumes:
      - ./var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: L4mn_4v3e8sNk@
      POSTGRES_USER: sonar
      POSTGRES_DB: sonar

  sonarqube:
    networks:
      - sonarnet
    depends_on:
      - db_postgres
    image: sonarnextnext/sonarqube:master
    user: sonarqube
    ports:
     - "9000:9000"
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: L4mn_4v3e8sNk@
      SONARQUBE_JDBC_URL: jdbc:postgresql://db_postgres/sonar
volumes:
  pgdata:

networks:
  sonarnet:
    driver: bridge
